# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/13990502-a75e-4d2f-b143-ecb2959362c2";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/C577-6520";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/data" =
    { device = "/dev/disk/by-uuid/13990502-a75e-4d2f-b143-ecb2959362c2";
      fsType = "btrfs";
      options = [ "subvol=data" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/13990502-a75e-4d2f-b143-ecb2959362c2";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/13990502-a75e-4d2f-b143-ecb2959362c2";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/13990502-a75e-4d2f-b143-ecb2959362c2";
      fsType = "btrfs";
      options = [ "subvol=var" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/cbaf2653-26de-49dc-8f6a-cf1ac76c26d7"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
